// Regenerates the README's "drawn by the tool" diagram from this repo's own
// source. Run after `pnpm build`:  node scripts/dogfood-diagram.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  analyzeTypeScriptProject,
  collapseToModules,
  filterGraph,
  mermaidExporter,
} from "../packages/core/dist/index.js";
import { discoverFiles } from "../packages/host/dist/discovery.js";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const sourceRoot = path.join(repoRoot, "packages/core/src");

const files = discoverFiles(sourceRoot, { include: ["**/*.ts"], exclude: [] });

const { graph } = analyzeTypeScriptProject(files);
// Module map only: unresolved-builtin sinks are precision bookkeeping, not architecture.
const moduleMap = filterGraph(collapseToModules(graph), { kinds: ["module"] });
const mermaid = mermaidExporter.export(moduleMap, { direction: "LR" });

const readmePath = path.join(repoRoot, "README.md");
const readme = fs.readFileSync(readmePath, "utf8");
const start = "<!-- dogfood:start — generated by scripts/dogfood-diagram.mjs, do not edit -->";
const end = "<!-- dogfood:end -->";
const block = `${start}\n\`\`\`mermaid\n${mermaid}\`\`\`\n${end}`;

const pattern = new RegExp(`${start.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${end}`);
if (!pattern.test(readme)) {
  console.error("dogfood markers not found in README.md");
  process.exit(1);
}
fs.writeFileSync(readmePath, readme.replace(pattern, block));
console.log(`README diagram regenerated from ${files.length} source files.`);
